# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-control-acceso"
BBFILE_PATTERN_meta-control-acceso = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-control-acceso = "6"

LAYERDEPENDS_meta-control-acceso = "core openembedded-layer meta-python raspberrypi"
LAYERSERIES_COMPAT_meta-control-acceso = "wrynose"
